version: '3'
services:
  # The PHP-FPM Service
  php:
    image: docker.io/library/php:8.5-fpm
    container_name: clp-php
    volumes:
      - ./htdocs:/home/clp-user/htdocs:z
    restart: always
    environment:
      DEVELOP: 1

  # The Nginx Service
  nginx:
    image: docker.io/library/nginx:alpine
    container_name: clp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:z
      - ./htdocs:/home/clp-user/htdocs:z
    depends_on:
      - php
    restart: always